name: Django CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black flake8

    - name: Lint with flake8
      run: flake8 .

    - name: Check formatting with black
      run: black --check .

    - name: Apply database migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate --noinput  # Certifique-se de aplicar as migrações
    
    - name: Check migrations
      run: |
        python manage.py migrate --noinput
        python manage.py showmigrations

    - name: Run tests
      run: python manage.py test
